### ISSUE TITLE
Multiple locale support

### ISSUE THREAD

**Issue by Rus-Abd** [meilisearch/strapi-plugin-meilisearch#1024]
**Description**
Im using strapi v5 and strapi-plugin-meilisearch 0.13.1. All works fine for 1 default locale, but when I try to add others, I see only 2 documents in strapi melisearch panel, instead of 4 (2 en, 2 fr). And the docs seem to be contradicting on how the config for locales should be added. (I tried both ways)

**Screenshots or Logs**

![Image](https://github.com/user-attachments/assets/6bae3a4a-ee0d-453c-ac3f-b06342811630)

**Environment (please complete the following information):**
- Meilisearch version: [e.g. v.1.13.0]
- strapi-plugin-meilisearch version: [e.g v0.13.1]
- Strapi version: [e.g. v5.10.3]

**Comment by Rus-Abd** [comment]
![Image](https://github.com/user-attachments/assets/ef69ac29-ef3b-48d5-ae25-68492bbd434b)
![Image](https://github.com/user-attachments/assets/c2c93df8-9133-4cac-974d-74902ea443aa)
this is what happens every time when I click on the tick mark in the panel, to add my collection to meilisearch

**Comment by lemps** [comment]
This seems fixed in the tag 0.13.2 but for some reason a release has not been made

**Comment by Rus-Abd** [comment]
@lemps any idea when it's going to happen?

**Comment by Yordan-Ramchev** [comment]
This issue should be reopened as release 0.13.2 is still not published in npm https://www.npmjs.com/package/strapi-plugin-meilisearch?activeTab=versions

**Comment by Strift** [comment]
At last, [v0.13.2](https://github.com/meilisearch/strapi-plugin-meilisearch/releases/tag/v0.13.2) has been published on NPM: https://www.npmjs.com/package/strapi-plugin-meilisearch

Please let us know if you encounter any issues 🙏
